name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
        exclude:
          - os: windows-latest
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Build
        env:
          GOOS: ${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }}
          GOARCH: ${{ matrix.arch }}
        run: |
          mkdir -p dist
          go build -o dist/stressit-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows-latest' && '.exe' || '' }} .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stressit-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/

  upload-release-assets:
    needs: build
    runs-on: ubuntu-latest
    name: Release pushed tag
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Stable Release: ${tag#v}" \
              --generate-notes

      - name: Upload to Release (Linux)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release upload "Stable Release: ${tag}" dist/stressit-ubuntu-latest-amd64

      - name: Upload to Release (macOS)
        run: |
          gh release upload "Stable Release: ${tag}" dist/stressit-macos-latest-amd64
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Upload to Release (Windows)
        run: |
          gh release upload "Stable Release: ${tag}" dist/stressit-windows-latest-amd64.exe
        env:
          GITHUB_TOKEN: ${{ github.token }}
          tag: ${{ github.ref_name }}